spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost/kobalttown?connectionCollation=utf8mb4_unicode_520_ci&allowPublicKeyRetrieval=true&useSSL=false
      username: local
      password: "r))jK=HtmT;Xd4bfm*=oLy+m37o6a62.7agvHaNLg*AX4AT8H"
  jpa:
    open-in-view: false
    show-sql: false
